sudo: required
dist: trusty
git:
  depth: 1
language: node_js
node_js:
- '6'
- '7'
- stable
cache:
  directories:
  - node_modules
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
matrix:
  fast_finish: true
install:
- npm install
before_script:
- export DBUS_SESSION_BUS_ADDRESS=/dev/null
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- chmod +x $TRAVIS_BUILD_DIR/.travis/deploy_stage.sh
- chmod +x $TRAVIS_BUILD_DIR/.travis/deploy.sh
script:
- npm run test:ci
- echo $TRAVIS_BRANCH
- if [ $TRAVIS_BRANCH = 'develop' ]; then npm run build:ci $S3_STAGE_REGION/$S3_STAGE_BUCKET/$APP_NAME/
  --base-href /pages/$APP_NAME-stage/; fi
- if [ $TRAVIS_BRANCH = 'master' ]; then npm run build:ci $S3_REGION/$S3_BUCKET/$APP_NAME/
  --base-href /pages/$APP_NAME/; fi
after_success:
- "./node_modules/.bin/codecov"
notifications:
  slack: blendtec:a5Z5i4z3iuWbHHDdlMRSMkiB
deploy:
- provider: s3
  region: us-west-1
  access_key_id: $AMAZON_ACCESS_KEY_ID
  secret_access_key:
    secure: $AMAZON_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  local-dir: dist
  upload-dir: $APP_NAME
  skip_cleanup: true
  acl: public_read
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: "./.travis/deploy.sh $S3_REGION/$S3_BUCKET/$APP_NAME"
  on:
    branch: master
- provider: s3
  region: us-west-1
  access_key_id: $AMAZON_ACCESS_KEY_ID
  secret_access_key:
    secure: $AMAZON_SECRET_ACCESS_KEY
  bucket: $S3_STAGE_BUCKET
  local-dir: dist
  upload-dir: $APP_NAME
  skip_cleanup: true
  acl: public_read
  on:
    branch: develop
- provider: script
  skip_cleanup: true
  script: "./.travis/deploy_stage.sh $S3_STAGE_REGION/$S3_STAGE_BUCKET/$APP_NAME
  on:
    branch: develop
