sudo: required
dist: trusty
git:
  depth: 1
language: node_js
node_js:
- '6'
- '7'
- stable
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
matrix:
  fast_finish: true
install:
- npm install
before_script:
- export DBUS_SESSION_BUS_ADDRESS=/dev/null
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run test:ci
- echo $TRAVIS_BRANCH
- if [ $TRAVIS_BRANCH = 'develop' ]; then npm run build:ci https://s3-us-west-1.amazonaws.com/recipe-stage-client.blendtec.com/dealer-application/
  --base-href /pages/dealer-application-stage/; fi
- if [ $TRAVIS_BRANCH = 'master' ]; then npm run build:ci https://s3-us-west-1.amazonaws.com/recipe-client.blendtec.com/dealer-application/
  --base-href /pages/dealer-application/; fi
after_success:
- "./node_modules/.bin/codecov"
notifications:
  slack: blendtec:a5Z5i4z3iuWbHHDdlMRSMkiB
env:
  global:
  - secure: Z7Xd9gvYOWrB1kbMrhpJkViIPVmmCPcq+IJjALAHhv8S6KFwXM3Xyc+LmQHzvS66gpNpkK7z93/btHBf7NXRrclisAm/Qv4XEeBOVEcMRWn4LaF1HzI/XvRBOxN2iju9n6YoDKTCe2/eRKSVZ2HFfjaAq5mLiTn0vrleKIERJQsXpBLbJA2kGr8myw9FWVLpTyei8QSs95Q+cEkGrnlLQL37wWpGlxA/JVDbjGWlDs/MDlggA+K6wTzZQfurzKRg6pwcie8S6aMZPn2Juh77uNJnlKrDTV6Op5lzHPHbVRB9dWqhktQwxmU+BLP6mXAEJpLPJ+geav9evRQUnhh4Aqo1ZCqStycsNDHh8ZyyWGxv6z/0f1kJYDrRqCjEBDe2asNNBVNqfmJIJhWtiAT76ZX/1KkPcGGVlEfwOB2hEsYTAcd4lQzC4cBAuU+bX6IcAhUARFAiaPlEE70PHxJiTn54XffWel1n26jet7JS/HQLq81KlU1qQflEbsonFlNlipyJz5GPIQ1fILbrIINBFNpw1HeEJk3D/c4aqMrzLFz1w7DjxQLWNJUCUbIuTpmT0Phk/7+FkHDUnzXTS/6gJLkdelQ1yBxZeyemngNU0EsnX5a5BmKh2/6oOAK6ISpP0ZGMr7rWRM1MHkorcu/2giDvhL/EsJTTqhnR3v1nulc=
  - secure: SmFjkUnFrG+p+j4s5rqCLuh6tEVmakA8zTrdSmt6Vv8YeoNvnIMgVRlauMgb3EFrnsBgj2w9ZYU75wiYHVVRCdPqy2HS935KVX/5k78CUrbRhqIFWO2jJqDimWedO1VdNj5kNrq5i/jQvc8bogwdMHbbAunIbKhuJc62VuDc70/wEUbRCirpciPrxp2wX6EeZQKFkaMeWdCHQ8XVY/7sGdxHXLEIuzqGNjyzsqQ8znOHWmArJ9m89afnmKojk9jUeARlB7DGZPLeHj871ked+nbMwDSEkdWNZcOnDM2GDWsZ0StfgHvMH+3VWq0ATPoU/3kPz9G9KWcyGc7CsRlwj09W0iNGB3akH7DPE0PvsjgJuSmvS3SJORIl+liMvOEFNXXHu59HviTEsfhfyyYa8uXwlCJkE8/jqWU6nb0l4KTCmLu8dBFBAEqnwRZLuEGeqD0J71JUxAOwFLsa3OmGIslvxtMsoqt6OH+6xj4lTKSnZTykpwEbigRlmTo/McCmjMg38B0DcPv0mnJHo+wMpho2m5x42Y1wePBxJDDTbfsAa53B0AcK/iRsJkku3ZdGbCJhoMkj+eB0Fo6Gj5M9ww+L80lHMdg58ertq1Rhc0daj6nxImU5uK1ICn5YevoKblaxuiQ7ihBpn0mjWVVqwWMzI8rN4hdycezeWVGTBcE=
  - secure: T7y9/V77BA5gFYfPcbLP7x5/AbL9oPq/B7iCwqV4XXqpWewjDMjrybAAeWvygRUhE7/WorFsgpg1Mz27JjEGElo0YiSRDwbOKBrQhyqMYawuAAUrrzaG0vXWs2gzJJT3Iv/gxler/TAxVkZ6BCRi4AoVFUZcwJRkmlQD9s45ey3yIm2nXNfGkD+Oteo9kUq4JQov5aCRooPLK7boOJZ2yzfZ/MCgo6NTl7a1XlUl9B9gl3SSBBXAlIGzPl7MVF0g2ryRnOM9qhZYVreOxOaqzijeMe3EP5X17uxbQQoQ9zRASkcWj48C1hl3eW8x1GDWbpG6KivSbWDAX/Ct6H2f0cG+MXY4+0NWEyPrWBxqW5idAIn6pTGtSyvFnrVyF6Y4UcV8Go1n+Gixcn3ONAU8LO6ug8Iu4ui+OLYbbMH69KmQDr1be/5daT7qrem9zNrXZjMn0iSZjmud+aYR2XvyOI/hAfwTYXFpoZ1ql+8PyxxMn0KYn5mojGGCZXS2tUXbZWe86GB7YSPbIyM2j2BHzgngo/isH2ZBUzC2tTKZerlSCApp/uwZaiBdtptfO/0ykN29GCk79Lqcp2E9gFv/UCMuDb2XaLzSPGJeSyOHki/h2e3EWZ5XRzyRcA0VFyeX4oCdGGcK4tYuC5sx+uNFMQqMd50SIORZkYkxicnvr6A=
  - secure: OE5M8s4RKzJZz8eD9wflv4M1+M9o0RdOx9NP0pX+xEoGf1K0N3VCW7VpV1QJxPKEr6wOi2Ggago+vJ060mIliwqxE70q/M0DVEuDSRO1HCSrsXXIVgJQ4uH8Vwno6oVVMd7w7FVHl9C2DEQBIM57I0EansLPUjy35fbZtBu5F9QnfSWzMPaYiLHy0RjuEflR7eMfnEXasFMZr1Svlilk7/XnhSXr4Omo3f5LQPtKoVZBZmacl/nSEZ9QVGUTKKIiMYC2rS/ydy+nNQmzUa5t7ReziVcoKm3Uyfbjy5ovxa2rpEHKVqh/Eg0YtkKAt0Ry4pV3mR8FSeY8Gg7BUJgNqj6z9h7C/uCZiDMJyOypCAQ9xejAubdmLOW92aEh7By+Nz2gs4NnFUn2GSw5cKkLpmLZFcfDkkuwyQ+kT2LoGE1u8PwjxV0yywmasV5Tt5q0ZS4snHY/wB3HY6fQjYXWHSf9DpUNMSVVd0vhX7JUWrhLvFe4ZkjOulyhN542qfrqFbw69epx9wPQxfhOEvPPZAdZm36JdGaNI1ZtYk6H1H9ZCuMDCk/sg3+t5l/PvKvVhhUePIR0r3cHOstm+zLQq7AbT6u59tuPSVSX4TaaAs+p/b2K+e3qQhNcx9VUlGOau43QWaV2e33UcrFrUaxbkwI4bPS6FDXxMqQvi28MezI=
  - secure: HM8hrZuYCLkjJ17C9EsPqieIbPYTznNu7kS3pRpC/Fb98Jpot1P4SH183fL/YHyPMS9mEa8fpP0Bt0wr5RMkoboPKuLe0wVJr1otz33dk9zb6755+VXivZbS+FqdSUH0RfY9yv/jxYXQ9h5+TemjJvJdLQOXrafltYyTgL5oR7OlSWkS1p6fvbCKDCUhZ4BD7KeVdSayA0IhOj4f6HcIHJDFhhyWe/GoutxUG/ZJevnz3ZiWZr+sqqAJ9I8wuZ/Ju6CGd/IirT77XOCvOq3IhcIfGPOxVGvD0SsTSQWBhxdaT+c05wwzK7npFhmvQ8YufevgZWVvZeLDmTZM2SlB+r63ukhFqb5qp4a+SMQNwgg6KD/yLkr5GhagV+6AFQOdHMDwtItbAuTV10yNaNYefDddpncU7h1RLACq5t+OSuKM8x3zKvLvudK8Q1FAiKtbedqlMrHgGwFjlHKndsAqiLCsQZGzcOfnSaSX2tDW7Fluat6duvpmTNGsXgyaFOOt2evHzVkEeSql5T8HU24KDtwy8WL43nRQAgk22I09UODNRKFhOk+dVxGwwgN6gtyPvPFmxFa3VTcbUW8iL7s4Q3Nmq2vPBnjz4LzIP4YmRTzKwfgfE1XVEm9aJxT0SYOg7gAFITZ8FVRqwLuYCbwZpFiYxdwzC5GAayAr5KtfeaI=
  - secure: Z9co7gImKpAUlkxzpTTyyA20YiA3lL/Q3KHIsOStwhSwhcU+i2n/wl3qYsNlErnjg7haIwJaZkyKrYDKWjdzBKRV+JAaer5pn3ej8NYfXponrtD1FZ+HVCGLqZZGAf8haWztLUYoB4yWmoC1ghRPCXZG0lv/T5+4qt7uGQmoEAFAq1PLIGASSs/mWEwdMTjpSjeNte7A24kXDkTWWW09RafAQe71jO82/xE27irNk4c+1BEfPRaDtUKC9Mym9ZneJK+e8QUxaM8MX3VtUwwmnocJGLODC7m4OxAZvwVyUNEPl686UqWRPw+LY4LQ/67Qg8+gUhDGajHUow6cq+3vBrukqsH4ZhmXGmMgsxv4cmjxW161VMiLohoRum4ltJpEl3Ldv862F2V2hlLmwD0fTlqvdsIfH+FuWV10gYgXdpdnObjJ2V1FMns/XUFGgRqabKKmD3xXkyDL7uiKEWqPAwVixZVsFCenPtNsUbyA8E4b5ZtMVAPsjnWZyJqQNnNN/xL9gLgSU1LIuOd6e8Xptv2h5hlk7XwLGCuWNd9oeWOhDlWQV81f/tV+k78Sn1soeA4cjxJQY9EcMGRTwvGkq4CspTJBbKQ8RC0gsLW7PimvrAsLjDeLuI8TDiWM0t8PcHtQ/gB+txiGS+RWJYANKD4twh9HcJ3LjykZhl2couE=
deploy:
- provider: s3
  region: us-west-1
  access_key_id: AKIAJLMSNKBUNB4P3L4Q
  secret_access_key:
    secure: MO2vCEsQJX6PcELsP2zJ4RGlW3E80lIF7XVQg8yHF2gMt0T8R8ew4Uq2weCVB6iamsh4doNTRuSFZksMsUJ4+V50inMxW/NnYj/6mNf18VtynlntXwMKrH2zbORwv7ZTm+lXj6OCmXCjh3ic0YISFcXjAC4jwE1Ag2cm+XzQRXxYnHcmceu7WV/bgnnw/FogsWa2bNdwLVehYyEsxKveOaVel19bNuFAlA68vacAqp1RJV4vv1elg+nbFMP8bw8ngSo6SYHETMXIy7VXcpAt6ynRA7kiZqqTahAMn9tov3Z5ZY0ecm0OGSoDaX2B+Kh1ArIeWMI0UGh/jEKHP3WWNKEkbmFGprXg3wH3DERF0EIna+t0vWzEpEEtKvqvm/ntW4Dh7HqdIcPybylNq9WtWonIiMIfhu7EqmlzK9uPB8c/FxRJVg08j45v0c+e2IJog9+DBSKA7zh0DLHrfR5wcWzvaJW5rJha5l7O4CntXUOxipJodztw+0bbmi7jmXOVPAUsipVFaomMiXn0HroAOS+WFkxsuaDcJ5y2gAVDa5BfTY66ZuL7SwitCUzU6xuHpBZSBX/Hjx3q8W0Abh/Sd6r/yybWKCPstwiDXrtwvMK2xanZKTuxTaHaqUFVFo49CuTO4Ym004cLzxVG25mSKqh4voZnfWS7OENRW+pnp0w=
  bucket: recipe-client.blendtec.com
  local-dir: dist
  upload-dir: dealer-application
  skip_cleanup: true
  acl: public_read
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: "./.travis/deploy.sh https://s3-us-west-1.amazonaws.com/recipe-client.blendtec.com/dealer-application"
  on:
    branch: master
- provider: s3
  region: us-west-1
  access_key_id: AKIAJLMSNKBUNB4P3L4Q
  secret_access_key:
    secure: MO2vCEsQJX6PcELsP2zJ4RGlW3E80lIF7XVQg8yHF2gMt0T8R8ew4Uq2weCVB6iamsh4doNTRuSFZksMsUJ4+V50inMxW/NnYj/6mNf18VtynlntXwMKrH2zbORwv7ZTm+lXj6OCmXCjh3ic0YISFcXjAC4jwE1Ag2cm+XzQRXxYnHcmceu7WV/bgnnw/FogsWa2bNdwLVehYyEsxKveOaVel19bNuFAlA68vacAqp1RJV4vv1elg+nbFMP8bw8ngSo6SYHETMXIy7VXcpAt6ynRA7kiZqqTahAMn9tov3Z5ZY0ecm0OGSoDaX2B+Kh1ArIeWMI0UGh/jEKHP3WWNKEkbmFGprXg3wH3DERF0EIna+t0vWzEpEEtKvqvm/ntW4Dh7HqdIcPybylNq9WtWonIiMIfhu7EqmlzK9uPB8c/FxRJVg08j45v0c+e2IJog9+DBSKA7zh0DLHrfR5wcWzvaJW5rJha5l7O4CntXUOxipJodztw+0bbmi7jmXOVPAUsipVFaomMiXn0HroAOS+WFkxsuaDcJ5y2gAVDa5BfTY66ZuL7SwitCUzU6xuHpBZSBX/Hjx3q8W0Abh/Sd6r/yybWKCPstwiDXrtwvMK2xanZKTuxTaHaqUFVFo49CuTO4Ym004cLzxVG25mSKqh4voZnfWS7OENRW+pnp0w=
  bucket: recipe-stage-client.blendtec.com
  local-dir: dist
  upload-dir: dealer-application
  skip_cleanup: true
  acl: public_read
  on:
    branch: develop
- provider: script
  skip_cleanup: true
  script: "./.travis/deploy_stage.sh https://s3-us-west-1.amazonaws.com/recipe-stage-client.blendtec.com/dealer-application"
  on:
    branch: develop
