sudo: required
dist: trusty
git:
  depth: 1
language: node_js
node_js:
- '6'
- '7'
- stable
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
matrix:
  fast_finish: true
install:
- npm install
before_script:
- export DBUS_SESSION_BUS_ADDRESS=/dev/null
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- chmod +x ./travis/deploy_stage.sh
- chmod +x ./travis/deploy.sh
script:
- npm run test:ci
- echo $TRAVIS_BRANCH
- if [ $TRAVIS_BRANCH = 'develop' ]; then npm run build:ci https://s3-us-west-1.amazonaws.com/recipe-stage-client.blendtec.com/dealer-application/
  --base-href /pages/dealer-application-stage/; fi
- if [ $TRAVIS_BRANCH = 'master' ]; then npm run build:ci https://s3-us-west-1.amazonaws.com/recipe-client.blendtec.com/dealer-application/
  --base-href /pages/dealer-application/; fi
after_success:
- "./node_modules/.bin/codecov"
notifications:
  slack: blendtec:a5Z5i4z3iuWbHHDdlMRSMkiB
deploy:
- provider: s3
  region: us-west-1
  access_key_id: $AMAZON_ACCESS_KEY_ID
  secret_access_key:
    secure: $AMAZON_SECRET_ACCESS_KEY
  bucket: recipe-client.blendtec.com
  local-dir: dist
  upload-dir: dealer-application
  skip_cleanup: true
  acl: public_read
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: "./.travis/deploy.sh https://s3-us-west-1.amazonaws.com/recipe-client.blendtec.com/dealer-application"
  on:
    branch: master
- provider: s3
  region: us-west-1
  access_key_id: $AMAZON_ACCESS_KEY_ID
  secret_access_key:
    secure: $AMAZON_SECRET_ACCESS_KEY
  bucket: recipe-stage-client.blendtec.com
  local-dir: dist
  upload-dir: dealer-application
  skip_cleanup: true
  acl: public_read
  on:
    branch: develop
- provider: script
  skip_cleanup: true
  script: './.travis/deploy_stage.sh https://s3-us-west-1.amazonaws.com/recipe-stage-client.blendtec.com/dealer-application'
  on:
    branch: develop
